language: julia
os:
  - linux
  - osx
julia:
#  - 0.7
  - nightly
matrix:
  allow_failures:
    julia: nightly
notifications:
  email: false
branches:
  only:
  - master
## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.build(); Pkg.test(; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("BEDFiles")); Pkg.add("Documenter"); Pkg.add("Query"); Pkg.add("CSV"); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("BEDFiles")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit_token(Codecov.process_folder())'
